services:
  myapp:
    build: .
    container_name: consumer
    ports:
      - "8081:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://producer_db:5432/hackaton
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - /home/eavila/hackaton/videos/input:/home/hackaton/videos/input
      - /home/eavila/hackaton/videos/output:/home/hackaton/videos/output
    networks:
      - hackaton_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis2025
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis2025", "ping | grep -q \"PONG\""]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - hackaton_net

networks:
  hackaton_net:
    name: hackaton_net
    external: true

volumes:
  pgdata:
  redis_data:




