spring:
  kafka:
    bootstrap-servers: 172.20.0.3:9092

  data:
    redis:
      host: 172.18.0.2

  datasource:
    url: jdbc:postgresql://localhost:5435/hackaton
    username: user
    password: password

app:
  video.input.path: /home/eavila/hackaton/videos/input
  video.output.path: /home/eavila/hackaton/videos/output