server:
  port: 8081

spring:
  data:
    redis:
      host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5435/hackaton
    username: user
    password: password

app:
  video.input.path: /home/eavila/hackaton/videos/input
  video.output.path: /home/eavila/hackaton/videos/output